# Generated by Django 4.2.4 on 2023-08-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_abstract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='abstract',
            field=models.FileField(blank=True, max_length=150, null=True, upload_to='pdf_files'),
        ),
    ]
