# Generated by Django 4.2.4 on 2023-08-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_abstract'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='quantity_available',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='investment_amount',
            field=models.IntegerField(choices=[(500000, 500000), (1000000, 1000000), (1500000, 1500000), (2000000, 2000000), (2500000, 2500000)]),
        ),
    ]
