# Generated by Django 4.2.4 on 2023-08-18 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_companymanagerprofile_options'),
        ('company', '0005_alter_company_valuation'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.companymanagerprofile'),
        ),
    ]
