# Generated by Django 4.2.4 on 2023-08-19 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_remove_company_investment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='last_year_revenue',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
