# Generated by Django 4.2.4 on 2023-08-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_company_last_year_revenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='quantity_available',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
