# Generated by Django 4.2.4 on 2023-08-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_alter_company_quantity_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cover_images'),
        ),
        migrations.AddField(
            model_name='company',
            name='valid',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
