# Generated by Django 4.2.4 on 2023-08-28 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_investor_bank_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Investor_Bank_Details',
        ),
    ]
