# Generated by Django 4.2.4 on 2023-09-01 19:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_investor_to_company_bank_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor_to_company_bank_details',
            name='equity',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
