# Generated by Django 4.2.4 on 2023-09-01 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_investor_to_company_bank_details_equity'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor_to_company_bank_details',
            name='Company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='company.company'),
        ),
    ]
