# Generated by Django 4.2.4 on 2023-09-01 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_investor_to_company_bank_details_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investor_to_company_bank_details',
            old_name='Company',
            new_name='company',
        ),
    ]
