# Generated by Django 4.2.4 on 2023-09-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_rename_company_investor_to_company_bank_details_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='last_year_revenue',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
