# Generated by Django 4.2.4 on 2023-08-15 11:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyManagerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=255, null=True)),
                ('mobile_number', models.IntegerField()),
                ('office_number', models.IntegerField()),
                ('founder', models.BooleanField(default=True)),
                ('designation', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('office_address', models.TextField()),
                ('office_pincode', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
