# Generated by Django 4.2.4 on 2023-08-16 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_companymanagerprofile_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyManagerProfile',
        ),
    ]
