# Generated by Django 4.2.4 on 2023-08-18 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companymanagerprofile',
            options={'verbose_name_plural': 'Company Manager Profile'},
        ),
    ]
