# Generated by Django 4.2.4 on 2023-08-31 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_companymanagerprofile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymanagerprofile',
            name='token',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
