# Generated by Django 4.2.4 on 2023-09-01 19:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_investor_to_company_bank_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investor_portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equity_purchased', models.DecimalField(decimal_places=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('price_paid', models.FloatField()),
                ('payment_id', models.CharField(max_length=100)),
                ('Investor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='company.company')),
            ],
        ),
    ]
