# Generated by Django 4.2.4 on 2023-09-01 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0002_investor_portfolio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investor_bank_details',
            options={'verbose_name_plural': 'Investors Bank Details'},
        ),
        migrations.AlterModelOptions(
            name='investor_portfolio',
            options={'verbose_name_plural': 'Investors Portfolios'},
        ),
    ]
