# Generated by Django 4.2.4 on 2023-09-02 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0004_investor_bank_details_investor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor_portfolio',
            name='equity_purchased',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
