# Generated by Django 4.2.4 on 2023-08-14 11:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_stage', models.CharField(max_length=150)),
                ('industry_category', models.CharField(max_length=180)),
                ('companyName', models.TextField()),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('abstract', models.FileField(max_length=150, upload_to='pdf_files')),
                ('last_month_revenue', models.FloatField()),
                ('second_last_month_revenue', models.FloatField()),
                ('third_last_month_revenue', models.FloatField()),
                ('investment_amount', models.FloatField()),
                ('equity', models.DecimalField(decimal_places=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('valuation', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.category')),
            ],
            options={
                'verbose_name_plural': 'Company',
            },
        ),
    ]
